server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
jwt:
  signerKey: "ELjnG67maSPb0PG8ropXO1mUgoVe6q4aDJmbkVmxXv0Z+zn6HtlDts7B4p9D7uUX"
  valid-duration: 3600 #in second
  refreshable - duration: 360000 #in seconds