name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.MY_GITHUB_TOKEN }} # Sử dụng bí mật bạn vừa tạo
        issue-message: "Be careful"              # Tin nhắn gửi đến khi có issue mới
        pr-message: "Just pull gently"           # Tin nhắn gửi đến khi có pull request mới
